name: Tests
on:
  push:
    branches: [main]
  pull_request:
jobs:
  phpunit:
    strategy:
      matrix:
        php_version: [7.4]
    runs-on: ubuntu-latest
    steps:
    # 检出代码
    - uses: actions/checkout@v2
    # 初始化 PHP 环境
    - name: Setup PHP environment
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php_version }}
        coverage: xdebug
    # 安装 composer 依赖
    - name: Install dependencies
      run: composer install
    # 执行 PHPUnit 测试
    - name: PHPUnit check
      run: ./vendor/bin/phpunit --coverage-text